apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: x402-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: x402-operator-role
subjects:
  - kind: ServiceAccount
    name: x402-operator
    namespace: x402-system
